baseURL = "https://www.prouvost.dev/"
languageCode = "en-us"
title = "Antoine Prouvost"
theme = "ezhil"
timeout=3000

[[menu.main]]
name = "About"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[params]
	subtitle= "Ph.D. Candidate"  # Page title (in tab)
	cv_name= "aprouvost-cv.pdf"

[[params.social]]
	name = "GitHub"
	icon = "github"
	url = "https://github.com/AntoinePrv"

[[params.social]]
	name = "Twitter"
	icon = "twitter"
	url = "https://twitter.com/AntoineProuvost"

[[params.social]]
	name = "Scholar"
	icon = "book-open"
	url = "https://scholar.google.com/citations?user=5k3Cll0AAAAJ&hl=en&oi=ao"

[[params.social]]
	name = "LinkedIn"
	icon = "linkedin"
	url = "https://www.linkedin.com/in/antoine-prouvost-0667b6a4/"
